---
spec:
  destination:
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/mikelaferriere/k8s-homelab.git
    targetRevision: HEAD

namespaces:
  - baby-buddy
  - cert-manager
  - homelab
  - immich
  - immich-frame
  - ingress-nginx
  - joplin
  - metallb-system
  - monitoring
  - mosquitto
  - nfs-provisioner
  - paperless-ngx
  - streaming
  - protonmail
  - security

applications:
  - name: authentik
    path: applications/authentik/
    destinationNamespace: security
  - name: baby-buddy
    path: applications/baby-buddy/
    destinationNamespace: baby-buddy
  - name: cert-manager
    path: applications/cert-manager/
    destinationNamespace: cert-manager
  - name: grafana
    path: applications/grafana/
    destinationNamespace: monitoring
  - name: hashicorp-vault
    path: applications/hashicorp-vault/
    destinationNamespace: security
    # see https://discuss.hashicorp.com/t/instaling-vault-through-argocd-workflow-agent-injector-cant-be-synced/32375/2
    ignoreDifferences:
      - group: admissionregistration.k8s.io
        kind: MutatingWebhookConfiguration
        jqPathExpressions:
          - .webhooks[]?.clientConfig.caBundle
  - name: headlamp
    path: applications/headlamp/
    destinationNamespace: monitoring
  - name: immich
    path: applications/immich/
    destinationNamespace: immich
  - name: immich-frame
    path: applications/immich-frame/
    destinationNamespace: immich
  - name: ingress-nginx
    path: applications/ingress-controller/
    destinationNamespace: ingress-nginx
  - name: loki
    path: applications/loki/
    destinationNamespace: monitoring
  - name: metallb
    path: applications/metallb/
    destinationNamespace: metallb-system
  - name: metrics-server
    path: applications/metrics-server/
    destinationNamespace: monitoring
  - name: nfs-provisioner-paperless
    path: applications/nfs-provisioner-paperless/
    destinationNamespace: nfs-provisioner
  - name: nfs-provisioner
    path: applications/nfs-provisioner/
    destinationNamespace: nfs-provisioner
  - name: paperless-ngx
    path: applications/paperless-ngx/
    destinationNamespace: paperless-ngx
  - name: plex
    path: applications/plex/
    destinationNamespace: streaming
  - name: prometheus
    path: applications/prometheus/
    destinationNamespace: monitoring
  - name: promtail
    path: applications/promtail/
    destinationNamespace: monitoring
  - name: homelab-api
    path: applications/homelab/api/
    destinationNamespace: homelab
  - name: homelab-dashboard
    path: applications/homelab/dashboard/
    destinationNamespace: homelab
  - name: homelab-event-bus
    path: applications/homelab/event-bus/
    destinationNamespace: homelab
  - name: homelab-websocket
    path: applications/homelab/websocket/
    destinationNamespace: homelab
  - name: homelab-speech-recognizer
    path: applications/homelab/speech-recognizer/
    destinationNamespace: homelab
  - name: homelab-speech-python
    path: applications/homelab/speech-python/
    destinationNamespace: homelab
  - name: homelab-scheduler
    path: applications/homelab/scheduler/
    destinationNamespace: homelab
  - name: mosquitto
    path: applications/mosquitto/
    destinationNamespace: mosquitto
  - name: pve-exporter
    path: applications/pve-exporter/
    destinationNamespace: monitoring
  - name: diun
    path: applications/diun/
    destinationNamespace: monitoring
  - name: external-services
    path: applications/external-services/
    destinationNamespace: homelab
  - name: protonmail
    path: applications/protonmail/
    destinationNamespace: protonmail
  - name: homepage
    path: applications/homepage/
    destinationNamespace: homelab
  - name: joplin
    path: applications/joplin/
    destinationNamespace: joplin

