---
loki:
  monitoring:
    dashboards:
      # -- If enabled, create configmap with dashboards for monitoring Loki
      enabled: false
    rules:
      # -- If enabled, create PrometheusRule resource with Loki recording rules
      enabled: false
    alerts:
      # -- If enabled, create PrometheusRule resource with Loki alerting rules
      enabled: false
    serviceMonitor:
      # -- If enabled, ServiceMonitor resources for Prometheus Operator are created
      enabled: true
    selfMonitoring:
      enabled: false
      grafanaAgent:
        installOperator: false
  #     lokiCanary:
  #       enabled: false

  test:
    enabled: false

  # minio:
  #   enabled: false

  singleBinary:
    replicas: 1

  loki:
    auth_enabled: false
    commonConfig:
      replication_factor: 1
    storage:
      type: 'filesystem'
    compactor:
      retention_enabled: true
      retention_delete_delay: 2h
      retention_delete_worker_count: 150
    limits_config:
      split_queries_by_interval: 24h
      max_query_parallelism: 100
      enforce_metric_name: false
      reject_old_samples: true
      reject_old_samples_max_age: 48h
      retention_period: 48h
    query_scheduler:
      max_outstanding_requests_per_tenant: 4096
    frontend:
      max_outstanding_per_tenant: 4096
