---
loki:
  monitoring:
    dashboards:
      # -- If enabled, create configmap with dashboards for monitoring Loki
      enabled: false
    rules:
      # -- If enabled, create PrometheusRule resource with Loki recording rules
      enabled: false
    alerts:
      # -- If enabled, create PrometheusRule resource with Loki alerting rules
      enabled: false
    serviceMonitor:
      # -- If enabled, ServiceMonitor resources for Prometheus Operator are created
      enabled: false
    selfMonitoring:
      enabled: false
      grafanaAgent:
        installOperator: false
      lokiCanary:
        enabled: false

  test:
    enabled: false

  minio:
    enabled: true

  loki:
    commonConfig:
      replication_factor: 1
    storage:
      type: 'filesystem'
  singleBinary:
    replicas: 1
