---
apiVersion: v1
kind: Service
metadata:
  annotations: {}
  labels:
    app: {{ .Values.app.name }}
  name: {{ .Values.app.name }}
spec:
  type: LoadBalancer
  ports:
    - name: "{{ .Values.app.name }}"
      port: {{ .Values.app.port }}
      targetPort: {{ .Values.app.targetPort }}
  selector:
    app: {{ .Values.app.name }}
status:
  loadBalancer: {}