---
mosquitto:
  auth:
    enabled: false
  service:
    type: LoadBalancer
  ingress:
    enabled: true
    className: nginx
    annotations:
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_set_header Upgrade "websocket";
      proxy_set_header Connection "Upgrade";
    hosts:
      - paths:
        - path: /ws/mqtt
          pathType: Prefix

