---
apiVersion: v1
kind: Service
metadata:
  name: hairpin-proxy
  namespace: hairpin-proxy
spec:
  selector:
    app: hairpin-proxy-haproxy
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443

