# Icons: https://github.com/homarr-labs/dashboard-icons/blob/main/ICONS.md
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.app.name }}-config-secrets
  labels:
    app.kubernetes.io/name: {{ .Values.app.name }}
data:
  LOG_LEVEL: debug
  HOMEPAGE_FILE_PLEX_KEY_PATH: /vault/secrets/plex_key
