---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}
spec:
  selector:
    name: {{ .Values.app.name }}
  ports:
    - port: 11434
      name: http
      targetPort: http
      protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}-code
spec:
  selector:
    name: {{ .Values.app.name }}-code
  ports:
    - port: 11434
      name: http
      targetPort: http
      protocol: TCP