---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}
spec:
  selector:
    name: {{ .Values.app.name }}
  type: LoadBalancer
  ports:
    - port: 80
      name: http
      targetPort: http
      protocol: TCP