---
grafana:
  service:
    type: LoadBalancer

  persistence:
    enabled: true
    type: pvc

  sidecar:
    # Beware of crazy JSON :/
    dashboards:
      enabled: true
    datasources:
      enabled: true
      initDatasources: true
      skipReload: false
      reloadUrl: http://grafana.monitoring.svc.cluster.local/api/admin/provisioning/datasources/reload
