---
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Values.app.name }}-config-laferriere
data:
  # Filters
  Albums: "4ff5dba3-cdbe-432d-bd6a-f4e37ea5b464"
  # ExcludedAlbums: "ALBUM3,ALBUM4"
  # People: "PERSON1,PERSON2"
  ShowMemories: "false"
  ImagesFromDays: ""
  ImagesFromDate: ""
  ImagesUntilDate: ""

