---
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Values.app.name }}-config
data:
  # TZ: "Europe/Berlin"

  # Required
  ImmichServerUrl: "https://immich.laferriere.app"
  # ApiKey: "KEY" // set with vault

  # Image
  ImageZoom: "false"  
  Interval: "30"
  TransitionDuration: "3"

  # Clock
  ShowClock: "true"
  ClockFormat: "h:mm"

  # Weather
  # WeatherApiKey: "API-KEY"
  # UnitSystem: "imperial"
  # Language: "en"
  # ShowWeatherDescription: "true"
  # WeatherLatLong: "40.730610, -73.935242"

  # Metadata
  ShowImageDesc: "false"
  ShowImageLocation: "false"
  ShowPhotoDate: "true"
  PhotoDateFormat: "MM-dd-yyyy"

  # Caching
  RenewImagesDuration: "1"
  DownloadImages: "false"
  RefreshAlbumPeopleInterval: "12"

  # UI
  # PrimaryColor: "#FF5733"
  PrimaryColor: "#FFF"
  BaseFontSize: "17px"

  # Misc
  ImmichFrameAlbumName: ""