---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations: {}
  labels:
    app: {{ .Values.app.name }}-laferriere
  name: {{ .Values.app.name }}-laferriere
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.app.name }}-laferriere
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: internal-app
        # vault.hashicorp.com/agent-inject-secret-defined: kv/data/secrets/homelab
        vault.hashicorp.com/agent-inject-template-init: |
          {{`{{- with secret "kv/data/secrets/immich" -}}
            export ApiKey='{{ .Data.data.MIKE_IMMICH_FRAME_API_KEY }}'
          {{- end }}`}}
      labels:
        app: {{ .Values.app.name }}-laferriere
    spec:
      containers:
        - name: {{ .Values.app.name }}-laferriere
          envFrom:
          - configMapRef:
              name: {{ .Values.app.name }}-config
          - configMapRef:
              name: {{ .Values.app.name }}-config-laferriere
          image: ghcr.io/immichframe/immichframe:latest
          command: ["sh", "-c", ". /vault/secrets/init && dotnet ImmichFrame.WebApi.dll"]
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "100Mi"
              cpu: "30m"
            limits:
              memory: "200Mi"
              cpu: "60m"
      restartPolicy: Always
status: {}