---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations: {}
  labels:
    app: {{ .Values.app.name }}-laferriere
  name: {{ .Values.app.name }}-laferriere
spec:
  replicas: 1
  revisionHistoryLimit: 3
  strategy:
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      app: {{ .Values.app.name }}-laferriere
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: internal-app
        # vault.hashicorp.com/agent-inject-secret-defined: kv/data/secrets/homelab
        vault.hashicorp.com/agent-inject-template-init: |
          {{`{{- with secret "kv/data/secrets/immich" -}}
            export ApiKey='{{ .Data.data.MIKE_IMMICH_FRAME_API_KEY }}'
          {{- end }}`}}
      labels:
        app: {{ .Values.app.name }}-laferriere
    spec:
      containers:
        - name: {{ .Values.app.name }}-laferriere
          envFrom:
          - configMapRef:
              name: {{ .Values.app.name }}-config
          - configMapRef:
              name: {{ .Values.app.name }}-config-laferriere
          image: ghcr.io/immichframe/immichframe:latest
          imagePullPolicy: Always
          command: ["sh", "-c", ". /vault/secrets/init && dotnet ImmichFrame.WebApi.dll"]
          ports:
            - containerPort: 8080
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 5
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 5
      restartPolicy: Always
status: {}