---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations: {}
  labels:
    app: {{ .Values.app.name }}
  name: {{ .Values.app.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: internal-app
        # vault.hashicorp.com/agent-inject-secret-defined: kv/data/secrets/homelab
        vault.hashicorp.com/agent-inject-template-init: |
          {{`{{- with secret "kv/data/secrets/immich" -}}
            export ApiKey='{{ .Data.data.MIKE_IMMICH_FRAME_API_KEY }}'
          {{- end }}`}}
      labels:
        app: {{ .Values.app.name }}
    spec:
      containers:
        - name: {{ .Values.app.name }}
          envFrom:
          - configMapRef:
              name: {{ .Values.app.name }}-config
          image: ghcr.io/immichframe/immichframe:latest
          command: ["sh", "-c", ". /vault/secrets/init && dotnet ImmichFrame.WebApi.dll"]
          # livenessProbe:
          #   exec:
          #     command:
          #       - curl
          #       - -f
          #       - http://localhost:{{ .Values.app.port }}
          #   failureThreshold: 5
          #   periodSeconds: 30
          #   timeoutSeconds: 10
          ports:
            - containerPort: {{ .Values.app.port }}
          resources:
            requests:
              memory: "150Mi"
              cpu: "100m"
            limits:
              memory: "300Mi"
              cpu: "200m"
      #     volumeMounts:
      #     - name: settingsjson
      #       mountPath: /app/Config
      # volumes:
      #   - name: settingsjson
      #     hostPath:
      #       path: /vault/secrets
      #       type: Directory
      restartPolicy: Always
status: {}