---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.app.name }}-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: letsencrypt-issuer-prod
spec:
  ingressClassName: nginx
  tls:
  - hosts:
      - laferriere.app
      - {{ .Values.ingress_prefix }}.laferriere.app
    secretName: {{ .Values.app.name }}-secret-prod
  rules:
  - host: {{ .Values.ingress_prefix }}.laferriere.app
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.app.name }}
            port:
              number: {{ .Values.app.port }}
