---
apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app: nvidia-smi
  name: nvidia-smi
spec:
  template:
    metadata:
      annotations: {}
      labels:
        app: nvidia-smi
    spec:
      runtimeClassName: nvidia
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: "nvidia.com/gpu"
                operator: In
                values:
                  - "true"
      tolerations:
        - key: "nvidia.com/gpu"
          operator: "Equal"
          value: "true"
          effect: "NoSchedule"
      containers:
        - name: nvidia-smi
          image: nvidia/cuda:12.4.0-base-ubuntu22.04
          command: ["nvidia-smi"]
          imagePullPolicy: Always
        - name: nvidia-smi-uuids
          image: nvidia/cuda:12.4.0-base-ubuntu22.04
          command: ["nvidia-smi", "--query-gpu=gpu_name,uuid", "--format=csv"]
          imagePullPolicy: Always
      restartPolicy: Never
status: {}

---
apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app: nvidia-device-test
  name: nvidia-device-test
spec:
  template:
    metadata:
      annotations: {}
      labels:
        app: nvidia-device-test
    spec:
      runtimeClassName: nvidia
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: "nvidia.com/gpu"
                operator: In
                values:
                  - "true"
      tolerations:
        - key: "nvidia.com/gpu"
          operator: "Equal"
          value: "true"
          effect: "NoSchedule"
      containers:
        - name: nvidia-device-test
          image: nvcr.io/nvidia/k8s/cuda-sample:vectoradd-cuda11.7.1-ubuntu20.04
          imagePullPolicy: Always
        #   resources:
        #     requests:
        #       nvidia.com/gpu: 1
        #     limits:
        #       nvidia.com/gpu: 2
      restartPolicy: Never
status: {}
