---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: protonmail-bridge-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: protonmail-bridge
  template:
    metadata:
      labels:
        app: protonmail-bridge
    spec:
      volumes: 
        - name: protonmail-data
          persistentVolumeClaim: 
            claimName: protonmail-bridge-pv-claim
      containers:
      - name: protonmail-bridge-container
        volumeMounts:
          - mountPath: "/root/"
            name: protonmail-data
        image: shenxn/protonmail-bridge:latest
        imagePullPolicy: Always
        ports:
          - containerPort: 25
          - containerPort: 143
        resources:
          requests:
            cpu: 50m
            memory: 200Mi
          limits: 
            cpu: 100m
            memory: 400Mi
        livenessProbe:
          tcpSocket:
            port: 25
          initialDelaySeconds: 5
          timeoutSeconds: 2
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 5
        readinessProbe:
          tcpSocket:
            port: 25
          initialDelaySeconds: 5
          timeoutSeconds: 2
          periodSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        startupProbe:
          tcpSocket:
            port: 25
          initialDelaySeconds: 5
          timeoutSeconds: 2
          periodSeconds: 5
          successThreshold: 1
          failureThreshold: 30
