---
apiVersion: v1
kind: Service
metadata:
  name: smtp-service
spec:
  selector:
    app: protonmail-bridge
  ports:
    - name: smtp
      port: 25
      targetPort: 25
    - name: imap
      port: 143
      targetPort: 143
