---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 8880
      targetPort: 8880
      protocol: TCP
  selector:
    app: {{ .Values.app.name }}
