apiVersion: v2
name: prometheus
version: 1.0.0
dependencies:
  - name: prometheus-operator-crds
    version: 11.0.0
    repository: https://prometheus-community.github.io/helm-charts
  - name: prometheus
    version: 25.19.1
    repository: https://prometheus-community.github.io/helm-charts
  - name: prometheus-postgres-exporter
    version: 6.0.0
    repository: https://prometheus-community.github.io/helm-charts
