---
prometheus:
  serverFiles:
    alerting_rules.yml:
      groups:
        - name: Instances
          rules:
            - alert: InstanceDown
              expr: up == 0
              for: 5m
              labels:
                severity: page
              annotations:
                description: '{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 5 minutes.'
                summary: 'Instance {{ $labels.instance }} down'
            - alert: PodRestarts
              annotations:
                message: Pod {{ $labels.namespace }}/{{ $labels.pod }} ({{ $labels.container}}) is restarting {{ printf "%.2f" $value }} times during the last hour.
              expr: increase(kube_pod_container_status_restarts_total{container!~"kubernetes-vault-renew"}[1h]) >= 1
              labels:
                severity: critical
  server:
    service:
      type: LoadBalancer
  extraScrapeConfigs: |
    - job_name: proxmox-pve
      static_configs:
        - targets:
          - 192.168.1.7
      metrics_path: /pve
      params:
        module: [ default ]
        cluster: ['1']
        node: ['1']
      relabel_configs:
        - source_labels: [ __address__ ]
          target_label: __param_target
        - source_labels: [ __param_target ]
          target_label: instance
        - target_label: __address__
          replacement: pve-exporter:9221
    - job_name: raspberry-pi
      static_configs:
        - targets:
          - 192.168.6.27:9100
          - 192.168.6.180:9100
          - 192.168.6.216:9100
      metrics_path: /metrics
      # params:
      #   module: [ default ]
      #   cluster: ['1']
      #   node: ['1']
      # relabel_configs:
      #   - source_labels: [ __address__ ]
      #     target_label: __param_target
      #   - source_labels: [ __param_target ]
      #     target_label: instance
      #   - target_label: __address__
      #     replacement: pve-exporter:9221

