---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: vault-database
spec:
  provider: vault
  parameters:
    vaultAddress: "http://hashicorp-vault.security.svc:8200"
    roleName: "internal-app"
    objects: |
      - objectName: "password"
        secretPath: "kv/data/authentik/postgresql"
        secretKey: "password"