---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations: {}
  labels:
    app: {{ .Values.app.name }}
  name: {{ .Values.app.name }}
spec:
  replicas: 1
  revisionHistoryLimit: 3
  strategy:
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
  template:
    metadata:
      annotations:
        diun.enable: "false"
      labels:
        app: {{ .Values.app.name }}
    spec:
      containers:
        - name: {{ .Values.app.name }}
          envFrom:
          - configMapRef:
              name: {{ .Values.app.name }}-config
          image: 10.10.10.199:5000/typescript/nx/{{ .Values.app.name }}:latest
          command: ["sh", "-c", "node /app/main.js"]
          livenessProbe:
            httpGet:
              port: {{ .Values.app.port }}
              path: /api/scheduler
            initialDelaySeconds: 30
            periodSeconds: 5
          readinessProbe:
            httpGet:
              port: {{ .Values.app.port }}
              path: /api/scheduler
            initialDelaySeconds: 30
            periodSeconds: 5
          ports:
            - containerPort: {{ .Values.app.port }}
          resources:
            requests:
              memory: "50Mi"
              cpu: "30m"
            limits:
              memory: "100Mi"
              cpu: "60m"
      restartPolicy: Always
status: {}