---
app_name: baby-buddy
ingress_prefix: babybuddy

postgresql:
  metrics:
    enabled: true
  fullnameOverride: postgresql
  auth:
    username: postgres
    password: postgres
    database: postgres