---
app_name: baby-buddy
ingress_prefix: babybuddy

postgresql:
  enabled: true
  metrics:
    enabled: true
  fullnameOverride: postgresql
  auth:
    username: postgres
    password: postgres
    database: postgres
  primary:
    resources:
      limits: {}
      requests:
        cpu: 250m
        memory: 256Mi
