apiVersion: v2
name: cert-manager
version: 1.0.0
dependencies:
  - name: cert-manager
    version: 1.14.4
    repository: https://charts.jetstack.io
  - name: reflector
    version: 7.1.262
    repository: https://emberstack.github.io/helm-charts

