---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: le-crt-staging
spec:
  secretName: tls-secret-staging
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-staging
  commonName: laferriere.app
  dnsNames:
    - laferriere.app
    - test.laferriere.app