---
kind: ConfigMap
apiVersion: v1
metadata:
  name: zoneminder-config
data:
  TX: America/New_York
  PUID: "99"
  PGID: "100"
  INSTALL_HOOK: "0"
  INSTALL_FACE: "0"
  INSTALL_TINY_YOLOV3: "0"
  INSTALL_YOLOV3: "0"
  INSTALL_TINY_YOLOV4: "0"
  INSTALL_YOLOV4: "0"
  MULTI_PORT_START: "0"
  MULTI_PORT_END: "0"

