---
apiVersion: v1
kind: Endpoints
metadata:
  name: zoneminder # Must be equal to Service name for automatic mapping
subsets:
- addresses:
  - ip: 192.168.1.125 # IP address of your external service that you would like to proxy requests to
  ports:
  - port: 80