---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: zoneminder-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: letsencrypt-issuer-prod
spec:
  ingressClassName: nginx
  tls:
  - hosts:
      - zm.laferriere.app
    secretName: zoneminder-prod
  rules:
  - host: zm.laferriere.app
    http:
      paths:
      - path: /zm
        pathType: Prefix
        backend:
          service:
            name: zoneminder
            port:
              number: 80
