---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: zoneminder
  name: cache-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
status: {}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: zoneminder
  name: data-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
status: {}
