---
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  # add an additional local user with apiKey and login capabilities
  #   apiKey - allows generating API keys
  #   login - allows to login using UI
  accounts.bot: apiKey
  # disables user. User is enabled by default
  accounts.bot.enabled: "true"
  policy.csv: |
    p, role:readonly-user, applications, get, default/homelab-*, allow
    p, role:readonly-user, applications, sync, default/homelab-*, allow
    p, role:readonly-user, applications, action/apps/Deployment/restart, default/myapp-*, allow
    p, role:readonly-user, exec, create, default/homelab-*, allow
    g, bot, role:readonly-user