---
authentik:
  global:
    env:
      - name: AUTHENTIK_SECRET_KEY
        # value: file:///vault/secrets/secret-key
        value: "as"

  #   podAnnotations:
  #     vault.hashicorp.com/agent-inject: "true"
  #     vault.hashicorp.com/agent-inject-status: "update"
  #     vault.hashicorp.com/role: 'internal-app'
  #     vault.hashicorp.com/agent-inject-template-secret-key: |
  #       {{- with secret "authentik" -}}
  #       {{ .Data.secret-key }}
  #       {{- end }}
  #     vault.hashicorp.com/agent-inject-template-postgresql-password: |
  #       {{- with secret "authentik/postgresql" -}}
  #       {{ .Data.password }}
  #       {{- end }}

  #   deploymentAnnotations:
  #     vault.hashicorp.com/agent-inject: "true"
  #     vault.hashicorp.com/agent-inject-status: "update"
  #     vault.hashicorp.com/role: 'internal-app'
  #     vault.hashicorp.com/agent-inject-template-secret-key: |
  #       {{- with secret "authentik" -}}
  #       {{ .Data.secret-key }}
  #       {{- end }}
  #     vault.hashicorp.com/agent-inject-template-postgresql-password: |
  #       {{- with secret "authentik/postgresql" -}}
  #       {{ .Data.password }}
  #       {{- end }}

  # server:
  #   service:
  #     annotations:
  #       vault.hashicorp.com/agent-inject: "true"
  #       vault.hashicorp.com/agent-inject-status: "update"
  #       vault.hashicorp.com/role: 'internal-app'
  #       vault.hashicorp.com/agent-inject-template-secret-key: |
  #         {{- with secret "authentik" -}}
  #         {{ .Data.secret-key }}
  #         {{- end }}
  #       vault.hashicorp.com/agent-inject-template-postgresql-password: |
  #         {{- with secret "authentik/postgresql" -}}
  #         {{ .Data.password }}
  #         {{- end }}

  authentik:
    secret_key: "as"
    error_reporting:
      enabled: false
    postgresql:
      # password: file:///vault/secrets/postgresql-password
      password: ""

  postgresql:
    enabled: true
    auth:
      # password: file:///vault/secrets/postgresql-password
      password: ""

  redis:
    enabled: true
  # worker:
