---
authentik:
  global:
    env:
      - name: AUTHENTIK_SECRET_KEY
        value: file:///vault/secrets/secret-key
      - name: POSTGRES_PASSWORD_FILE
        value: /vault/secrets/postgresql-password

    deploymentAnnotations:
      vault.hashicorp.com/agent-inject: "true"
      vault.hashicorp.com/agent-inject-status: "update"
      vault.hashicorp.com/role: 'internal-app'
      vault.hashicorp.com/agent-inject-template-secret-key: |
        {{- with secret "kv/data/authentik" -}}
        {{ index .Data.data "secret-key" }}
        {{- end }}
      vault.hashicorp.com/agent-inject-template-postgresql-password: |
        {{- with secret "kv/data/authentik/postgresql" -}}
        {{ .Data.password }}
        {{- end }}


    podAnnotations:
      vault.hashicorp.com/agent-inject: "true"
      vault.hashicorp.com/agent-inject-status: "update"
      vault.hashicorp.com/role: 'internal-app'
      vault.hashicorp.com/agent-inject-template-secret-key: |
        {{- with secret "kv/data/authentik" -}}
        {{ index .Data.data "secret-key" }}
        {{- end }}
      vault.hashicorp.com/agent-inject-template-postgresql-password: |
        {{- with secret "kv/data/authentik/postgresql" -}}
        {{ .Data.password }}
        {{- end }}

  server:
    ingress:
      ingressClassName: nginx
      enabled: true
      hosts:
        - auth-k8s.laferriere.app

  authentik:
    secret_key: file:///vault/secrets/secret-key
    error_reporting:
      enabled: false
    postgresql:
      password: file:///vault/secrets/postgresql-password

  postgresql:
    enabled: true
    image:
      tag: 16.2.0
    auth:
      usePasswordFiles: true

    primary:
      extraVolumes:
        - name: secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "vault-database"
      extraVolumeMounts:
        - name: secrets-store-inline
          mountPath: "/vault/secrets/postgresql-password"
          readOnly: true
      extraEnvVars:
        - name: ALLOW_EMPTY_PASSWORD
          value: "true"
        - name: POSTGRES_PASSWORD_FILE
          value: /vault/secrets/postgresql-password

  redis:
    enabled: true

secret-store-csi-driver:
  syncSecret:
    enabled: true
