---
authentik:
  # global:
  #   env:
  #     - name: AUTHENTIK_SECRET_KEY
  #       # value: file:///vault/secrets/secret-key
  #       value: "as"

  #   podAnnotations:
  #     vault.hashicorp.com/agent-inject: "true"
  #     vault.hashicorp.com/agent-inject-status: "update"
  #     vault.hashicorp.com/role: 'internal-app'
  #     vault.hashicorp.com/agent-inject-template-secret-key: |
  #       {{- with secret "authentik" -}}
  #       {{ .Data.secret-key }}
  #       {{- end }}
  #     vault.hashicorp.com/agent-inject-template-postgresql-password: |
  #       {{- with secret "authentik/postgresql" -}}
  #       {{ .Data.password }}
  #       {{- end }}

  #   deploymentAnnotations:
  #     vault.hashicorp.com/agent-inject: "true"
  #     vault.hashicorp.com/agent-inject-status: "update"
  #     vault.hashicorp.com/role: 'internal-app'
  #     vault.hashicorp.com/agent-inject-template-secret-key: |
  #       {{- with secret "authentik" -}}
  #       {{ .Data.secret-key }}
  #       {{- end }}
  #     vault.hashicorp.com/agent-inject-template-postgresql-password: |
  #       {{- with secret "authentik/postgresql" -}}
  #       {{ .Data.password }}
  #       {{- end }}

  # server:
  #   service:
  #     type: LoadBalancer
  #     annotations:
  #       vault.hashicorp.com/agent-inject: "true"
  #       vault.hashicorp.com/agent-inject-status: "update"
  #       vault.hashicorp.com/role: 'internal-app'
  #       vault.hashicorp.com/agent-inject-template-secret-key: |
  #         {{- with secret "authentik" -}}
  #         {{ .Data.secret-key }}
  #         {{- end }}
  #       vault.hashicorp.com/agent-inject-template-postgresql-password: |
  #         {{- with secret "authentik/postgresql" -}}
  #         {{ .Data.password }}
  #         {{- end }}

  # authentik:
  #   secret_key: "as"
  #   error_reporting:
  #     enabled: false
    # postgresql:
    #   # password: file:///vault/secrets/postgresql-password
    #   password: "a"

  # postgresql:
  #   enabled: true
  #   auth:
  #     # password: file:///vault/secrets/postgresql-password
  #     password: "a"

  # redis:
  #   enabled: true
  # worker:



  authentik:
    log_level: debug
    secret_key: "PleaseGenerateA50CharKey"
    # This sends anonymous usage-data, stack traces on errors and
    # performance data to authentik.error-reporting.a7k.io, and is fully opt-in
    error_reporting:
      enabled: false
    postgresql:
      password: "ThisIsNotASecurePassword"

  # server:
  #   ingress:
  #     enabled: true
  #     hosts:
  #       - authentik.domain.tld

  postgresql:
    enabled: true
    image:
      tag: 16.2.0
    auth:
      password: "ThisIsNotASecurePassword"

  redis:
    enabled: true