---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations: {}
  labels:
    app: {{ .Values.app.name }}
  name: {{ .Values.app.name }}
spec:
  replicas: 1
  revisionHistoryLimit: 5
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
  template:
    metadata:
      annotations: {}
      labels:
        app: {{ .Values.app.name }}
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: dedicated
                operator: In
                values:
                  - gpu
      tolerations:
        - key: "dedicated"
          operator: "Equal"
          value: "gpu"
          effect: "NoSchedule"
      containers:
        - name: {{ .Values.app.name }}
          image: plexinc/pms-docker:plexpass
          imagePullPolicy: Always
          resources:
            limits:
              cpu: "1024m"
              memory: "6Gi"
            requests:
              memory: "5Gi"
              cpu: "512m"
          envFrom:
          - configMapRef:
              name: {{ .Values.app.name }}-config
          volumeMounts:
            - mountPath: /config
              name: config-claim
            - mountPath: /transcode
              name: transcode-claim
            - mountPath: /data/media
              name: nfs-media
          livenessProbe:
            initialDelaySeconds: 60
            periodSeconds: 5
            tcpSocket:
              port: 32400
          ports:
            - name: plex-port
              containerPort: 32400
              protocol: TCP
            - containerPort: 1900
              protocol: UDP
            - containerPort: 32469
              protocol: TCP
            - containerPort: 5353
              protocol: UDP
            - containerPort: 8324
              protocol: TCP
            - containerPort: 32410
              protocol: UDP
            - containerPort: 32412
              protocol: UDP
            - containerPort: 32413
              protocol: UDP
            - containerPort: 32414
              protocol: UDP
      restartPolicy: Always
      volumes:
        - name: transcode-claim
          persistentVolumeClaim:
            claimName: transcode-claim
        - name: config-claim
          persistentVolumeClaim:
            claimName: config-claim
        - name: nfs-media
          nfs:
            server: 192.168.1.22
            path: /volume1/Shared
status: {}

