---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations: {}
  labels:
    app: {{ .Values.app.name }}
  name: {{ .Values.app.name }}
spec:
  replicas: 1
  revisionHistoryLimit: 2
  strategy:
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
  template:
    metadata:
      annotations: {}
      labels:
        app: {{ .Values.app.name }}
    spec:
      nodeName: "k8s-gpu-godzilla"
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: "nvidia.com/gpu"
                operator: In
                values:
                  - "true"
      tolerations:
        - key: "nvidia.com/gpu"
          operator: "Equal"
          value: "true"
          effect: "NoSchedule"
      containers:
        - name: {{ .Values.app.name }}
          image: lscr.io/linuxserver/plex:latest
          imagePullPolicy: Always
          resources:
            requests:
              memory: "1500Mi"
              cpu: "500m"
            limits:
              cpu: "3"
              memory: "6000Mi"
          envFrom:
          - configMapRef:
              name: {{ .Values.app.name }}-config
          volumeMounts:
            - mountPath: /config
              name: config
            - mountPath: /transcode
              name: transcode-claim
            - mountPath: /data/media
              name: nfs-media
          livenessProbe:
            initialDelaySeconds: 60
            periodSeconds: 5
            tcpSocket:
              port: 32400
          ports:
            - name: plex-port
              containerPort: 32400
              protocol: TCP
            - containerPort: 1900
              protocol: UDP
            - containerPort: 32469
              protocol: TCP
            - containerPort: 5353
              protocol: UDP
            - containerPort: 8324
              protocol: TCP
            - containerPort: 32410
              protocol: UDP
            - containerPort: 32412
              protocol: UDP
            - containerPort: 32413
              protocol: UDP
            - containerPort: 32414
              protocol: UDP
      restartPolicy: Always
      volumes:
        - name: transcode-claim
          persistentVolumeClaim:
            claimName: transcode-claim
        - name: config
          hostPath:
            path: /mnt/plex/config
            type: Directory
        - name: nfs-media
          nfs:
            server: 192.168.1.22
            path: /volume1/Shared
status: {}

