---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.app.name }}-ingress
  annotations:
    kubernetes.io/ingress.class: "gpu"
    cert-manager.io/cluster-issuer: letsencrypt-issuer-prod

    # # for the default ingress-nginx
    # nginx.ingress.kubernetes.io/proxy-connect-timeout: "3600"
    # nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    # nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
spec:
  ingressClassName: gpu
  tls:
  - hosts:
      - laferriere.media
      - {{ .Values.app.name }}.laferriere.media
    secretName: {{ .Values.app.name }}-secret-prod
  rules:
  - host: {{ .Values.app.name }}.laferriere.media
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.app.name }}-tcp
            port:
              number: 32400
