---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}-tcp
  annotations:
    metallb.universe.tf/allow-shared-ip: plex  # < annotation name to combine the Service IP, make sure it's same name as in the service UDP yaml
spec:
  type: LoadBalancer
  ports:
    - name: plex-port # Plex Media Server
      port: 32400
      targetPort: 32400
    - name: dnla-tcp-port # Plex DLNA Server
      port: 32469
      targetPort: 32469
      protocol: TCP
    - name: roku-port # Plex for Roku via Plex Companion
      port: 8324
      targetPort: 8324
      protocol: TCP
  selector:
    app: {{ .Values.app.name }}


---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}-udp
  annotations:
    metallb.universe.tf/allow-shared-ip: plex  # < annotation name to combine the Service IP, make sure it's same name as in the service UDP yaml
spec:
  ports:
    - name: dnla-udp-port # Plex DLNA Server
      port: 1900
      targetPort: 1900
      protocol: UDP
    - name: bon-avahi-port # Bonjour/Avahi network discovery
      port: 5353
      targetPort: 5353
      protocol: UDP
    - name: gdm-port-1 # GDM network discovery
      port: 32410
      targetPort: 32410
      protocol: UDP
    - name: gdm-port-2 # GDM network discovery
      port: 32412
      targetPort: 32412
      protocol: UDP
    - name: gdm-port-3 # GDM network discovery
      port: 32413
      targetPort: 32413
      protocol: UDP
    - name: gdm-port-4 # GDM network discovery
      port: 32414
      targetPort: 32414
      protocol: UDP
  selector:
    app: {{ .Values.app.name }}
