---
apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/loadBalancerIPs: 10.10.10.209
  labels:
    app: {{ .Values.app.name }}-app
  name: {{ .Values.app.name }}-app
spec:
  type: LoadBalancer
  ports:
    - name: http # Plex Media Server
      port: 32400
      targetPort: 32400
      protocol: TCP
    - name: dnla-udp-port # Plex DLNA Server
      port: 1900
      targetPort: 1900
      protocol: UDP
    - name: dnla-tcp-port # Plex DLNA Server
      port: 32469
      targetPort: 32469
      protocol: TCP
    - name: bon-avahi-port # Bonjour/Avahi network discovery
      port: 5353
      targetPort: 5353
      protocol: UDP
    - name: roku-port # Plex for Roku via Plex Companion
      port: 8324
      targetPort: 8324
      protocol: TCP
    - name: gdm-port-1 # GDM network discovery
      port: 32410
      targetPort: 32410
      protocol: UDP
    - name: gdm-port-2 # GDM network discovery
      port: 32412
      targetPort: 32412
      protocol: UDP
    - name: gdm-port-3 # GDM network discovery
      port: 32413
      targetPort: 32413
      protocol: UDP
    - name: gdm-port-4 # GDM network discovery
      port: 32414
      targetPort: 32414
      protocol: UDP
  selector:
    app: {{ .Values.app.name }}-app

