---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-photos
spec:
  capacity:
    storage: 300Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: nfs
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /volume1/photo
    server: 192.168.1.22