---
ingress-nginx:
  controller:
    kind: DaemonSet
    metrics:
      enabled: true
    podAnnotations:
      prometheus.io/port: "10254"
      prometheus.io/scrape: "true"
    allowSnippetAnnotations: true
    service:
      LoadBalancerIP: 192.168.1.2
      # externalTrafficPolicy: Local
      annotations:
        metallb.universe.tf/address-pool: internal-ips
        # for the default ingress-nginx
        nginx.ingress.kubernetes.io/proxy-connect-timeout: "3600"
        nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
        nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
        nginx.ingress.kubernetes.io/server-snippets: |
          proxysetheader Upgrade $httpupgrade;
          proxyhttpversion 1.1;
          proxysetheader X-Forwarded-Host $httphost;
          proxysetheader X-Forwarded-Proto $scheme;
          proxysetheader X-Forwarded-For $remoteaddr;
          proxysetheader Host $host;
          proxysetheader Connection "upgrade";
          proxycachebypass $httpupgrade;

  tcp:
    1883: "mosquitto/mosquitto:1883"
    9001: "mosquitto/mosquitto:9001"
    10000: "homelab/event-bus:10000"
    10001: "homelab/speech-recognizer:10001"
    10002: "homelab/websocket:10002"
    11434: "ai/ollama-code:11434"
    32400: "streaming/plex:32400"

