---
internal-ingress:
  controller:
    electionID: internal-ingress-controller
    service:
      annotations:
        metallb.universe.tf/address-pool: internal-ips
    ingressClassResource:
      name: internal-nginx  # default: nginx
      enabled: true
      default: false
      controllerValue: "k8s.io/internal-ingress-nginx"  # default: k8s.io/ingress-nginx

external-ingress:
  controller:
    service:
      annotations:
        metallb.universe.tf/address-pool: external-ips
    electionID: external-ingress-controller
    ingressClassResource:
      name: external-nginx  # default: nginx
      enabled: true
      default: false
      controllerValue: "k8s.io/external-ingress-nginx"  # default: k8s.io/ingress-nginx
