---
ingress-nginx:
  controller:
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
        additionalLabels:
          release: prometheus
    allowSnippetAnnotations: true
    service:
      LoadBalancerIP: 192.168.1.2
      # externalTrafficPolicy: Local
      annotations:
        metallb.universe.tf/address-pool: internal-ips
  tcp:
    1883: "mosquitto/mosquitto:1883"
    9001: "mosquitto/mosquitto:9001"
    10000: "homelab/event-bus:10000"
    10001: "homelab/speech-recognizer:10001"
    10002: "homelab/websocket:10002"
