---
ingress-nginx:
  controller:
    metrics:
      enabled: true
    allowSnippetAnnotations: true
    service:
      LoadBalancerIP: 192.168.1.2
      # externalTrafficPolicy: Local
      annotations:
        nginx.ingress.kubernetes.io/proxy-read-timeout: 3600
        nginx.ingress.kubernetes.io/proxy-send-timeout: 3600
        nginx.ingress.kubernetes.io/configuration-snippet: |
          proxy_http_version 1.1;
          proxy_set_header Connection "Upgrade";
          proxy_set_header Upgrade $http_upgrade;
          proxy_set_header X-Forwarded-Host $http_host;
          proxy_set_header X-Forwarded-Proto $scheme;
          proxy_set_header X-Forwarded-For $remote_addr;
          proxy_set_header Host $host;
          proxy_cache_bypass $http_upgrade;
        metallb.universe.tf/address-pool: internal-ips
  tcp:
    1883: "mosquitto/mosquitto:1883"
    9001: "mosquitto/mosquitto:9001"
    10000: "homelab/event-bus:10000"
    10001: "homelab/speech-recognizer:10001"
    10002: "homelab/websocket:10002"
