---
app:
  name: api
  port: 8081
  consumers: [
    "calendar-events",
    "fitbit-update",
    "hue-rooms",
    "sports-fetch-new-scores",
    "sports-scoreboard",
    "sports-sync-scores",
    "weather-current",
    "weather-hourly",
    "withings-update"
  ]

postgresql:
  metrics:
    enabled: true
  fullnameOverride: postgresql
  auth:
    username: postgres
    password: postgres
    database: postgres

