---
app:
  name: api
  port: 8081
  consumers: [
    "baby-buddy",
    "calendar-events",
    "fitbit-sync",
    "hue-sync",
    "sports-fetch-new-scores",
    "sports-scoreboard-sync",
    "sports-scores-sync",
    "weather-current-sync",
    "weather-hourly-sync",
    "withings-sync"
  ]

postgresql:
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
  fullnameOverride: postgresql
  auth:
    username: postgres
    password: postgres
    database: postgres
  primary:
    resources:
      limits: {}
      requests:
        cpu: 250m
        memory: 256Mi

