---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: speech-ingress
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /api/v2/speech
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.app.name }}
            port:
              number: {{ .Values.app.port }}

