---
apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/loadBalancerIPs: 10.10.10.213
  labels:
    app: {{ .Values.app.name }}
  name: {{ .Values.app.name }}
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: {{ .Values.app.port }}
      targetPort: {{ .Values.app.port }}
  selector:
    app: {{ .Values.app.name }}

