---
app:
  name: "paperless-ngx"
  storageClass: "nfs-paperless"

secret-store-csi-driver:
  syncSecret:
    enabled: true

postgresql:
    metrics:
      enabled: true
    auth:
      username: "paperless"
      database: "paperless"
      usePasswordFiles: true

    primary:
      resources:
        limits: {}
        requests:
          cpu: 250m
          memory: 256Mi
      extraVolumes:
        - name: vault-database
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "vault-database"
      extraVolumeMounts:
        - name: vault-database
          mountPath: "/vault/secrets/pg_password"
          readOnly: true
      extraEnvVars:
        - name: ALLOW_EMPTY_PASSWORD
          value: "true"
        - name: POSTGRES_PASSWORD_FILE
          value: /mnt/secrets-store/pg_password

redis:
  architecture: standalone
  auth:
    enabled: false
  commonConfiguration: |-
    # Enable AOF https://redis.io/topics/persistence#append-only-file
    appendonly no
