---
app:
  name: "paperless-ngx"
  storageClass: "nfs-documents-test"

postgresql:
  auth:
    username: "paperless"
    password: "paperless"
    database: "paperless"

redis:
  auth:
    enabled: false
  replica:
    replicaCount: 1
