---
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Values.app.name }}-config
data:
  ENVIRONMENT: production
  EVENT_BUS_HOST: ws://event-bus:10000
  MQTT_BROKER: ws://mosquitto.mosquitto.svc
  PROXY_HOST: http://192.168.1.117
  PGUSER: postgres
  PGPASSWORD: postgres
  PGDATABASE: postgres
  PGHOST: postgresql