---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations: {}
  labels:
    app: consumers
  name: consumers
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consumers
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        diun.enable: "false"
      labels:
        app: consumers
    spec:
      containers:
        {{- range $consumer := .Values.app.consumers }}
        - name: {{ $consumer }}
          envFrom:
          - configMapRef:
              name: {{ $.Values.app.name }}-config
          image: 10.10.10.199:5000/typescript/nx/consumer:latest
          command: ["sh", "-c", "node {{ $consumer }}/main.js"]
          resources:
            requests:
              memory: "50Mi"
              cpu: "50m"
            limits:
              memory: "100Mi"
              cpu: "100m"
        {{- end }}
      restartPolicy: Always
status: {}