---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations: {}
  labels:
    app: consumer
  name: consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consumer
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        diun.enable: "false"
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: internal-app
        # vault.hashicorp.com/agent-inject-secret-defined: kv/data/secrets/homelab
        vault.hashicorp.com/agent-inject-template-init: |
          {{`{{- with secret "kv/data/secrets/babybuddy" -}}
            export BABY_BUDDY_TOKEN={{ .Data.data.API_TOKEN }}
          {{- end }}`}}
      labels:
        app: consumer
    spec:
      containers:
        {{- range $consumer := .Values.app.consumers }}
        - name: {{ $consumer }}
          envFrom:
          - configMapRef:
              name: {{ $.Values.app.name }}-config
          image: 10.10.10.199:5000/typescript/nx/consumer:latest
          command: ["sh", "-c", ". /vault/secrets/init && node {{ $consumer }}/main.js"]
          resources:
            requests:
              memory: "50Mi"
              cpu: "50m"
            limits:
              memory: "100Mi"
              cpu: "100m"
        {{- end }}
      restartPolicy: Always
status: {}