---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}
spec:
  selector:
    name: {{ .Values.app.name }}
  type: LoadBalancer
  ports:
    - port: 8000
      name: http
      targetPort: http
      protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}-nextjs
spec:
  selector:
    name: {{ .Values.app.name }}-nextjs
  ports:
    - port: 3000
      name: http
      targetPort: http
      protocol: TCP