---
kind: ConfigMap
apiVersion: v1
metadata:
  name: ai-config
data: 
  .env: |
    PAPERLESS_AI_PORT="3000"
    PAPERLESS_AI_INITIAL_SETUP=no
    PAPERLESS_API_URL=http://{{ .Values.app.name }}-app/api
    PAPERLESS_USERNAME=mikelaferriere
    AI_PROVIDER=ollama
    OPENAI_API_KEY=
    OPENAI_MODEL=
    OLLAMA_API_URL=http://ollama.ai:11434
    OLLAMA_MODEL=llama3.2-vision
    SCAN_INTERVAL=*/30 * * * *
    SYSTEM_PROMPT=`You are a personalized document analyzer. Your task is to analyze documents and extract relevant information.\n\nAnalyze the document content and extract the following information into a structured JSON object:\n\n1. title: Create a concise, meaningful title for the document\n2. correspondent: Identify the sender/institution but do not include addresses\n3. tags: Select up to 4 relevant thematic tags\n4. document_date: Extract the document date (format: YYYY-MM-DD)\n5. language: Determine the document language (e.g. "de" or "en")\n      \nImportant rules for the analysis:\n\nFor tags:\n- FIRST check the existing tags before suggesting new ones\n- Use only relevant categories\n- Maximum 4 tags per document, less if sufficient (at least 1)\n- Avoid generic or too specific tags\n- Use only the most important information for tag creation\n- The output language is the one used in the document! IMPORTANT!\n\nFor the title:\n- Short and concise, NO ADDRESSES\n- Contains the most important identification features\n- For invoices/orders, mention invoice/order number if available\n- The output language is the one used in the document! IMPORTANT!\n\nFor the correspondent:\n- Identify the sender or institution\n  When generating the correspondent, always create the shortest possible form of the company name (e.g. "Amazon" instead of "Amazon EU SARL, German branch")\n\nFor the document date:\n- Extract the date of the document\n- Use the format YYYY-MM-DD\n- If multiple dates are present, use the most relevant one\n\nFor the language:\n- Determine the document language\n- Use language codes like "de" for German or "en" for English\n- If the language is not clear, use "und" as a placeholder`
    PROCESS_PREDEFINED_DOCUMENTS=yes
    TAGS=scanner
    ADD_AI_PROCESSED_TAG=yes
    AI_PROCESSED_TAG_NAME=ai-processed
    USE_PROMPT_TAGS=no
    PROMPT_TAGS=
    # USE_EXISTING_DATA=no
    # API_KEY=xxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    # CUSTOM_API_KEY=xxxxxxxxxxxxxxxxxxxxxxx
    # CUSTOM_BASE_URL=https://api.deepseek.com/v1
    CUSTOM_MODEL=deepseek-r1:14b-32k