---
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Values.app.name }}-config
data:
  PAPERLESS_SECRET_KEY: "generate a long secret or make one up"
  PAPERLESS_DBHOST: postgresql
  PAPERLESS_REDIS: "redis"
  PAPERLESS_TIKA_ENABLED: "1"
  PAPERLESS_TIKA_ENDPOINT: http://{{ .Values.app.name }}-ocr:9998
  PAPERLESS_TIKA_GOTENBERG_ENDPOINT: http://{{ .Values.app.name }}-ocr:3000
  PAPERLESS_TIME_ZONE: America/New_York
  PAPERLESS_OCR_LANGUAGE: "eng"
  PAPERLESS_CONSUMER_RECURSIVE: "true"
  PAPERLESS_CONSUMER_SUBDIRS_AS_TAGS: "true"
