---
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Values.app.name }}-config
data:
  USERMAP_UID: "0"
  USERMAP_GID: "0"
  PAPERLESS_TIME_ZONE: America/New_York
  PAPERLESS_TASK_WORKERS: "2"

  PAPERLESS_SECRET_KEY_FILE: file:///vault/secrets/secretkey
  PAPERLESS_ADMIN_USER_FILE: file:///vault/secrets/admin_user
  PAPERLESS_ADMIN_PASSWORD_FILE: file:///vault/secrets/admin_password

  PAPERLESS_DBPASS_FILE: file:///vault/secrets/pg_password
  PAPERLESS_REDIS: redis://{{ .Values.app.name }}-redis-master
  PAPERLESS_TIKA_ENABLED: "1"
  PAPERLESS_TIKA_ENDPOINT: http://{{ .Values.app.name }}-ocr:9998
  PAPERLESS_TIKA_GOTENBERG_ENDPOINT: http://{{ .Values.app.name }}-ocr:3000
  PAPERLESS_OCR_LANGUAGE: "eng"
  PAPERLESS_CONSUMER_POLLING: "60"
  PAPERLESS_CONSUMER_RECURSIVE: "true"
  PAPERLESS_CONSUMER_SUBDIRS_AS_TAGS: "true"
