---
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Values.app.name }}-config
data:
  PAPERLESS_DBHOST: {{ .Values.app.name }}-postgresql
  PAPERLESS_REDIS: redis://{{ .Values.app.name }}-redis-master
  PAPERLESS_TIKA_ENABLED: "1"
  PAPERLESS_TIKA_ENDPOINT: http://{{ .Values.app.name }}-ocr:9998
  PAPERLESS_TIKA_GOTENBERG_ENDPOINT: http://{{ .Values.app.name }}-ocr:3000
  PAPERLESS_TIME_ZONE: America/New_York
  PAPERLESS_OCR_LANGUAGE: "eng"
  PAPERLESS_CONSUMER_POLLING: "60"
  PAPERLESS_CONSUMER_RECURSIVE: "true"
  PAPERLESS_CONSUMER_SUBDIRS_AS_TAGS: "true"
  USERMAP_UID: "0"
  USERMAP_GID: "0"
