---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tika-deployment
  labels:
    app: tika
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tika
  template:
    metadata:
      labels:
        app: tika
    spec:
      containers:
      - name: tika
        image: ghcr.io/paperless-ngx/tika:latest
        imagePullPolicy: Always