---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations: {}
  labels:
    app: {{ .Values.app.name }}-app
  name: {{ .Values.app.name }}-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.app.name }}-app
  strategy:
    type: Recreate
  template:
    metadata:
      # annotations:
      #   vault.hashicorp.com/agent-inject: "true"
      #   vault.hashicorp.com/agent-inject-status: "update"
      #   vault.hashicorp.com/role: 'internal-app'
      #   # vault.hashicorp.com/agent-inject-secret-secret-key: 'kv/data/secrets/paperless'
      #   vault.hashicorp.com/agent-inject-template-secret-key: |
      #     {{`{{ with secret "kv/data/secrets/paperless" }}
      #     export PAPERLESS_SECRET_KEY={{ .Data.data.secretkey }}
      #     export PAPERLESS_ADMIN_USER={{ .Data.data.admin_user }}
      #     export PAPERLESS_ADMIN_PASSWORD={{ .Data.data.admin_password }}
      #     {{ end }}`}}
      #   # vault.hashicorp.com/agent-inject-secret-postgresql-password: 'kv/data/secrets/paperless/postgresql'
      #   vault.hashicorp.com/agent-inject-template-postgresql-password: |
      #     {{`{{ with secret "kv/data/secrets/paperless/postgresql" }}
      #     export PAPERLESS_DBPASS={{ .Data.data.password }}
      #     {{ end }}`}}
      labels:
        app: {{ .Values.app.name }}-app
    spec:
      containers:
        - name: {{ .Values.app.name }}-app
          envFrom:
          - configMapRef:
              name: {{ .Values.app.name }}-config   
          image: ghcr.io/paperless-ngx/paperless-ngx:latest
          livenessProbe:
            exec:
              command:
                - curl
                - -f
                - http://localhost:8000
            failureThreshold: 5
            periodSeconds: 30
            timeoutSeconds: 10
          ports:
            - containerPort: 8000
          resources: {}
          volumeMounts:
            - mountPath: /usr/src/paperless/data
              name: data-claim
            - mountPath: /usr/src/paperless/media
              name: media-claim
            - mountPath: /usr/src/paperless/export
              name: export-claim
            - mountPath: /usr/src/paperless/consume
              name: paperless-consume
      restartPolicy: Always
      volumes:
        - name: data-claim
          persistentVolumeClaim:
            claimName: data-claim
        - name: media-claim
          persistentVolumeClaim:
            claimName: media-claim
        - name: export-claim
          persistentVolumeClaim:
            claimName: export-claim
        - name: paperless-consume
          nfs:
            server: 192.168.1.22
            path: /volume1/doc-test/consume
status: {}