---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations: {}
  labels:
    app: {{ .Values.app.name }}-app
  name: {{ .Values.app.name }}-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.app.name }}-app
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}-app
    spec:
      containers:
        - name: {{ .Values.app.name }}-scanner
          image: manuc66/node-hp-scan-to:latest
          imagePullPolicy: IfNotPresent
          resources: {}
          envFrom:
          - configMapRef:
              name: scanner-config
          volumeMounts:
            - mountPath: /scan
              name: paperless-scanner
        - name: {{ .Values.app.name }}-app
          envFrom:
          - configMapRef:
              name: {{ .Values.app.name }}-config
          image: ghcr.io/paperless-ngx/paperless-ngx:2.11.0
          imagePullPolicy: IfNotPresent
          livenessProbe:
            exec:
              command:
                - curl
                - -f
                - http://localhost:8000
            failureThreshold: 5
            periodSeconds: 30
            timeoutSeconds: 10
          ports:
            - containerPort: 8000
          resources: {}
          volumeMounts:
            - mountPath: /usr/src/paperless/data
              name: data-claim
            - mountPath: /usr/src/paperless/media
              name: media-claim
            - mountPath: /usr/src/paperless/export
              name: export-claim
            - mountPath: /usr/src/paperless/consume
              name: paperless-consume
            - name: vault-database
              mountPath: "/mnt/secrets-store"
              readOnly: true
      restartPolicy: Always
      volumes:
        - name: vault-database
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "vault-database"
        - name: data-claim
          persistentVolumeClaim:
            claimName: data-claim
        - name: media-claim
          persistentVolumeClaim:
            claimName: media-claim
        - name: export-claim
          persistentVolumeClaim:
            claimName: export-claim
        - name: paperless-consume
          nfs:
            server: 192.168.1.22
            path: /volume1/paperless/consume
        - name: paperless-scanner
          nfs:
            server: 192.168.1.22
            path: /volume1/paperless/consume/scanner
status: {}