---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations: {}
  labels:
    app: {{ .Values.app.name }}-ocr
  name: {{ .Values.app.name }}-ocr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.app.name }}-ocr
  strategy: {}
  template:
    metadata:
      annotations: {}
      labels:
        app: {{ .Values.app.name }}-ocr
    spec:
      containers:
        - name: gotenberg
          image: docker.io/gotenberg/gotenberg:8.13.0
          command:
            - "gotenberg"
            - "--chromium-disable-javascript=true"
            - "--chromium-allow-list=file:///tmp/."
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: 50m
              memory: 20Mi
            limits: 
              cpu: 100m
              memory: 100Mi
          livenessProbe:
            tcpSocket:
              port: 3000
            initialDelaySeconds: 5
            timeoutSeconds: 2
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 5
          readinessProbe:
            tcpSocket:
              port: 3000
            initialDelaySeconds: 5
            timeoutSeconds: 2
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          startupProbe:
            tcpSocket:
              port: 3000
            initialDelaySeconds: 5
            timeoutSeconds: 2
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 30
        - name: tika
          image: ghcr.io/paperless-ngx/tika:2.9.1-full
          ports:
            - containerPort: 9998
          resources:
            requests:
              cpu: 50m
              memory: 300Mi
            limits: 
              cpu: 150m
              memory: 1Gi
          livenessProbe:
            tcpSocket:
              port: 9998
            initialDelaySeconds: 5
            timeoutSeconds: 2
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 5
          readinessProbe:
            tcpSocket:
              port: 9998
            initialDelaySeconds: 5
            timeoutSeconds: 2
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          startupProbe:
            tcpSocket:
              port: 9998
            initialDelaySeconds: 5
            timeoutSeconds: 2
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 30
      restartPolicy: Always
status: {}