---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations: {}
  labels:
    app: {{ .Values.app.name }}-app
  name: {{ .Values.app.name }}-app
spec:
  replicas: 1
  revisionHistoryLimit: 2
  strategy:
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      app: {{ .Values.app.name }}-app
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: internal-app
        # vault.hashicorp.com/agent-inject-secret-defined: kv/data/secrets/homelab
        vault.hashicorp.com/agent-inject-template-gpt-init: |
          {{`{{- with secret "kv/data/secrets/paperless" -}}
            export PAPERLESS_API_TOKEN={{ .Data.data.PAPERLESS_API_KEY }}
          {{- end }}`}}
      labels:
        app: {{ .Values.app.name }}-app
    spec:
      containers:
        - name: {{ .Values.app.name }}-app
          envFrom:
          - configMapRef:
              name: {{ .Values.app.name }}-config
          image: ghcr.io/paperless-ngx/paperless-ngx:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          resources:
            requests:
              cpu: 500m
              memory: 1250Mi
            limits: 
              cpu: 1
              memory: 2Gi
          livenessProbe:
            tcpSocket:
              port: 8000
            initialDelaySeconds: 5
            timeoutSeconds: 2
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 5
          readinessProbe:
            tcpSocket:
              port: 8000
            initialDelaySeconds: 5
            timeoutSeconds: 2
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          startupProbe:
            tcpSocket:
              port: 8000
            initialDelaySeconds: 5
            timeoutSeconds: 2
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 30
          volumeMounts:
            - mountPath: /usr/src/paperless/data
              name: data-claim
            - mountPath: /usr/src/paperless/media
              name: media-claim
            - mountPath: /usr/src/paperless/export
              name: export-claim
            - mountPath: /usr/src/paperless/consume
              name: paperless-consume
            - name: vault-database
              mountPath: "/mnt/secrets-store"
              readOnly: true
      restartPolicy: Always
      volumes:
        - name: vault-database
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "vault-database"
        - name: data-claim
          persistentVolumeClaim:
            claimName: data-claim
        - name: media-claim
          persistentVolumeClaim:
            claimName: media-claim
        - name: export-claim
          persistentVolumeClaim:
            claimName: export-claim
        - name: paperless-consume
          nfs:
            server: 192.168.1.22
            path: /volume1/paperless/consume
        - name: paperless-scanner
          nfs:
            server: 192.168.1.22
            path: /volume1/paperless/consume/scanner
status: {}