---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gotenberg-deployment
  labels:
    app: gotenberg
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gotenberg
  template:
    metadata:
      labels:
        app: gotenberg
    spec:
      containers:
      - name: tigotenbergka
        image: ghcr.io/paperless-ngx/gotenberg:latest
        pullImage: Always
        command:
          - "gotenberg"
          - "--chromium-disable-javascript=true"
          - "--chromium-allow-list=file:///tmp/."