---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations: {}
  labels:
    app: {{ .Values.app.name }}-app
  name: {{ .Values.app.name }}-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.app.name }}-app
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: internal-app
        # vault.hashicorp.com/agent-inject-secret-defined: kv/data/secrets/homelab
        vault.hashicorp.com/agent-inject-template-gpt-init: |
          {{`{{- with secret "kv/data/secrets/paperless" -}}
            export PAPERLESS_API_TOKEN={{ .Data.data.PAPERLESS_API_KEY }}
          {{- end }}`}}
      labels:
        app: {{ .Values.app.name }}-app
    spec:
      containers:
        - name: {{ .Values.app.name }}-gpt
          image: icereed/paperless-gpt:latest
          command: ["sh", "-c", ". /vault/secrets/gpt-init && /app/paperless-gpt"]
          imagePullPolicy: Always
          envFrom:
          - configMapRef:
              name: gpt-config
          volumeMounts:
            - mountPath: /prompts
              name: paperless-gpt
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: 50Mi
              cpu: 50m
            limits:
              memory: 100Mi
              cpu: 100m
        - name: {{ .Values.app.name }}-scanner
          image: manuc66/node-hp-scan-to:latest
          imagePullPolicy: Always
          envFrom:
          - configMapRef:
              name: scanner-config
          volumeMounts:
            - mountPath: /scan
              name: paperless-scanner
          resources:
            requests:
              memory: 50Mi
              cpu: 30m
            limits:
              memory: 100Mi
              cpu: 60m
        - name: {{ .Values.app.name }}-app
          envFrom:
          - configMapRef:
              name: {{ .Values.app.name }}-config
          image: ghcr.io/paperless-ngx/paperless-ngx:2.14.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          resources:
            requests:
              memory: 750Mi
              cpu: 300m
            limits:
              memory: 1500Mi
              cpu: 600m
          volumeMounts:
            - mountPath: /usr/src/paperless/data
              name: data-claim
            - mountPath: /usr/src/paperless/media
              name: media-claim
            - mountPath: /usr/src/paperless/export
              name: export-claim
            - mountPath: /usr/src/paperless/consume
              name: paperless-consume
            - name: vault-database
              mountPath: "/mnt/secrets-store"
              readOnly: true
      restartPolicy: Always
      volumes:
        - name: vault-database
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "vault-database"
        - name: data-claim
          persistentVolumeClaim:
            claimName: data-claim
        - name: media-claim
          persistentVolumeClaim:
            claimName: media-claim
        - name: export-claim
          persistentVolumeClaim:
            claimName: export-claim
        - name: paperless-consume
          nfs:
            server: 192.168.1.22
            path: /volume1/paperless/consume
        - name: paperless-scanner
          nfs:
            server: 192.168.1.22
            path: /volume1/paperless/consume/scanner
        - name: paperless-gpt
          nfs:
            server: 192.168.1.22
            path: /volume1/paperless/gpt
status: {}