---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: {{ .Values.app.name }}-claim
  name: {{ .Values.app.name }}-claim
spec:
  storageClassName: {{ .Values.app.storageClass }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
status: {}