---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: vault-database
spec:
  provider: vault
  parameters:
    vaultAddress: http://hashicorp-vault.security.svc:8200
    roleName: internal-app
    objects: |
      - objectName: pg_password
        secretPath: kv/data/secrets/paperless
        secretKey: PAPERLESS_DBPASS
      - objectName: secretkey
        secretPath: kv/data/secrets/paperless
        secretKey: PAPERLESS_SECRET_KEY
      - objectName: admin_user
        secretPath: kv/data/secrets/paperless
        secretKey: PAPERLESS_ADMIN_USER
      - objectName: admin_password
        secretPath: kv/data/secrets/paperless
        secretKey: PAPERLESS_ADMIN_PASSWORD
      - objectName: providers_json
        secretPath: kv/data/secrets/paperless
        secretKey: PAPERLESS_SOCIALACCOUNT_PROVIDERS

