---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: vault-database
spec:
  provider: vault
  parameters:
    vaultAddress: http://hashicorp-vault.security.svc:8200
    roleName: internal-app
    objects: |
      - objectName: pg_password
        secretPath: kv/data/secrets/paperless/postgresql
        secretKey: password
      - objectName: secretkey
        secretPath: kv/data/secrets/paperless
        secretKey: secretkey
      - objectName: admin_user
        secretPath: kv/data/secrets/paperless
        secretKey: admin_user
      - objectName: admin_password
        secretPath: kv/data/secrets/paperless
        secretKey: admin_password