---
apiVersion: v1
kind: Service
metadata:
  annotations: {}
  labels:
    app: {{ .Values.app.name }}-app
  name: {{ .Values.app.name }}-app
spec:
  # annotations:
  #   metallb.universe.tf/loadBalancerIPs: 10.10.10.202
  type: LoadBalancer
  ports:
    - name: "{{ .Values.app.name }}-app"
      port: 80
      targetPort: 8000
  selector:
    app: {{ .Values.app.name }}-app
status:
  loadBalancer: {}