---
apiVersion: v1
kind: Service
metadata:
  annotations: {}
  labels:
    app: {{ .Values.app.name }}-app
  name: {{ .Values.app.name }}-app
spec:
  type: NodePort
  ports:
    - name: "{{ .Values.app.name }}-app"
      port: 8000
      targetPort: 8000
      nodePort: 30083
  selector:
    app: {{ .Values.app.name }}-app
status:
  loadBalancer: {}