---
apiVersion: v1
kind: Service
metadata:
  annotations: {}
  labels:
    app: {{ .Values.app.name }}-ocr
  name: {{ .Values.app.name }}-ocr
spec:
  ports:
    - name: gotenberg
      port: 3000
      targetPort: 3000
    - name: tika
      port: 9998
      targetPort: 9998
  selector:
    app: {{ .Values.app.name }}-ocr