---
joplin-server:

  env:
    # -- Set the container timezone
    TZ: UTC
    # -- joplin-server base URL
    APP_BASE_URL: https://joplin.laferriere.app
    # -- joplin-server listening port (same as Service port)
    APP_PORT: 22300
    # -- Use pg for postgres
    DB_CLIENT: pg
    # -- Postgres DB Host
    POSTGRES_HOST: joplin-postgresql
    # -- Postgres DB port
    POSTGRES_PORT: "5432"
    # -- Postgres DB name
    POSTGRES_DATABASE: joplin
    # -- Postgres DB Username
    POSTGRES_USER: joplin
    # -- Postgres DB password
    POSTGRES_PASSWORD: joplin-pass

  ingress:
    main:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "nginx"
        cert-manager.io/cluster-issuer: letsencrypt-issuer-prod
        # proxy-body-size is set to 0 to remove the body limit on file uploads
        nginx.ingress.kubernetes.io/proxy-body-size: "0"
      ingressClassName: nginx
      tls:
        - hosts:
          - joplin.laferriere.app
          secretName: joplin-secret
      hosts:
        - host: joplin.laferriere.app
          paths:
            - path: /
              backend:
              service:
                name: joplin-joplin-server
                port: 22300

  # -- Enable and configure postgresql database subchart under this key.
  #    For more options see [postgresql chart documentation](https://github.com/bitnami/charts/tree/master/bitnami/postgresql)
  # @default -- https://github.com/bitnami/charts/blob/master/bitnami/postgresql/values.yaml
  postgresql:
    enabled: true
    metrics:
      enabled: true
    auth:
      username: joplin
      password: joplin-pass
      database: joplin
    persistence:
      enabled: false
    primary:
      resources:
        limits: {}
        requests:
          cpu: 250m
          memory: 256Mi
