---
apiVersion: v1
kind: Service
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
  labels:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: ingress-nginx
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
    - name: https
      port: 443
      targetPort: 443
      protocol: TCP
    - name: proxied-tcp-1883
      port: 1883
      targetPort: 1883
      protocol: TCP
    - name: proxied-tcp-9001
      port: 9001
      targetPort: 9001
      protocol: TCP
    - name: proxied-tcp-10000
      port: 10000
      targetPort: 10000
      protocol: TCP
    - name: proxied-tcp-10001
      port: 10001
      targetPort: 10001
      protocol: TCP
    - name: proxied-tcp-10002
      port: 10002
      targetPort: 10002
      protocol: TCP
  selector:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: ingress-nginx