---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app_name }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.app_name }}
  replicas: 1
  revisionHistoryLimit: 2
  strategy:
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ .Values.app_name }}
    spec:
      containers:
        - name: {{ .Values.app_name }}
          image: lscr.io/linuxserver/babybuddy:latest
          imagePullPolicy: Always
          envFrom:
          - configMapRef:
              name: {{ .Values.app_name }}-config
          ports:
            - containerPort: 8000
          resources:
            requests:
              memory: "512Mi"
              cpu: "1024m"
            limits:
              memory: "1024Mi"
              cpu: "2048m"

