---
app:
  name: plex

plex-media-server:
  image:
    tag: plexpass
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: dedicated
              operator: In
              values:
              - gpu
    tolerations:
    - key: "dedicated"
      operator: "Equal"
      value: "gpu"
      effect: "NoSchedule"

  ingress:
    enabled: true
    ingressClassName: nginx
    url: https://plex.laferriere.media

