---
apiVersion: v1
kind: Secret
metadata:
  name: jaeger-datasource
  labels:
    grafana_datasource: 'true' # default value for: sidecar.datasources.label
stringData:
  jaeger.yaml: |-
    apiVersion: 1
    datasources:
      - name: Jaeger
        type: jaeger
        url: http://jaeger-query.monitoring.svc:16686
        jsonData:
          sslmode: 'disable' # disable/require/verify-ca/verify-full
        # <bool> allow users to edit datasources from the UI.
        editable: false