---
apiVersion: v1
kind: Secret
metadata:
  name: grafana-datasources
  labels:
    grafana_datasource: 'true' # default value for: sidecar.datasources.label
stringData:
  loki.yaml: |-
    apiVersion: 1
    datasources:
      - name: Loki
        type: loki
        url: http://loki-gateway.monitoring.svc
        jsonData:
          sslmode: 'disable' # disable/require/verify-ca/verify-full
        # <bool> allow users to edit datasources from the UI.
        editable: false