---
apiVersion: v1
kind: Secret
metadata:
  name: grafana-datasources
  labels:
    grafana_datasource: 'true' # default value for: sidecar.datasources.label
stringData:
  prometheus.yaml: |-
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        url: http://prometheus-server.monitoring.svc
        jsonData:
          sslmode: 'disable' # disable/require/verify-ca/verify-full
        # <bool> allow users to edit datasources from the UI.
        editable: false