---
apiVersion: v1
kind: ConfigMap
metadata:
  name: helm-config-map
data:
  plugin.yaml: |
    apiVersion: argoproj.io/v1alpha1
    kind: ConfigManagementPlugin
    metadata:
      name: helm-plugin
    spec:
      init:
        command: ["helm"]
        args: ["dependency update"]
