---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  annotations:
    argocd.argoproj.io/sync-wave: "-1"

---
apiVersion: v1
kind: Namespace
metadata:
  name: argo-cd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"

---
apiVersion: v1
kind: Namespace
metadata:
  name: metallb-system
  annotations:
    argocd.argoproj.io/sync-wave: "-1"

---
apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager
  annotations:
    argocd.argoproj.io/sync-wave: "-1"

---
apiVersion: v1
kind: Namespace
metadata:
  name: ingress-nginx
  annotations:
    argocd.argoproj.io/sync-wave: "-1"

---
apiVersion: v1
kind: Namespace
metadata:
  name: kubernetes-dashboard
  annotations:
    argocd.argoproj.io/sync-wave: "-1"

---
apiVersion: v1
kind: Namespace
metadata:
  name: nfs-provisioner
  annotations:
    argocd.argoproj.io/sync-wave: "-1"

---
apiVersion: v1
kind: Namespace
metadata:
  name: security
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
    
---
apiVersion: v1
kind: Namespace
metadata:
  name: paperless-ngx
  annotations:
    argocd.argoproj.io/sync-wave: "-1"

---
apiVersion: v1
kind: Namespace
metadata:
  name: immich
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
