---
apiVersion: v1
kind: Namespace
metadata:
  name: argo-cd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"

---
apiVersion: v1
kind: List
items: 
{{- range .Values.namespaces }}
  - apiVersion: v1
    kind: Namespace
    metadata:
      name: {{ . }}
      annotations:
        argocd.argoproj.io/sync-wave: "-1"
{{- end }}
