---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nfs-provisioner-paperless
  namespace: argo-cd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    path: ./applications/nfs-provisioner-paperless/
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: nfs-provisioner
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
