---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nfs-provisioner-01
  namespace: argo-cd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    path: ./applications/nfs-provisioner/
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
    helm:
      parameters:
        - name: "nfs.server"
          value: 192.168.1.22
        - name: "nfs.path"
          value: /volumeUSB1/usbshare
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: nfs-provisioner
  syncPolicy:
    automated:
      selfHeal: true