# https://docs.openwebui.com/getting-started/env-configuration
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Values.app.name }}-config
data:
  ENABLE_SIGNUP: "true"
  WEBUI_URL: "https://chat.laferriere.ai"
  ENABLE_CHANNELS: "true"

  # postgresql
  DATABASE_URL: postgresql://postgres:postgres@postgresql:5432/postgres

  # tika
  CONTENT_EXTRACTION_ENGINE: "Tika"
  TIKA_SERVER_URL: http://{{ .Values.app.name }}-tika:9998  

  # websocket support
  ENABLE_WEBSOCKET_SUPPORT: "true"
  WEBSOCKET_MANAGER: redis
  WEBSOCKET_REDIS_URL: redis://{{ .Values.app.name }}-redis:6379/0

  # ollama
  ENABLE_OLLAMA_API: "true"
  OLLAMA_BASE_URLS: "http://ollama:11434"
  USE_OLLAMA_DOCKER: "false"
  USE_CUDA_DOCKER: "false"

  # openai (use pipelines instead of actual openai)
  ENABLE_OPENAI_API: "true"
  OPENAI_API_KEY: "0p3n-w3bu!"
  OPENAI_API_BASE_URL: http://{{ .Values.app.name }}-pipelines:9099

  # rag
  RAG_EMBEDDING_ENGINE: "ollama"
  RAG_EMBEDDING_MODEL: "nomic-embed-text"
  ENABLE_RAG_HYBRID_SEARCH: "true"
  RAG_OLLAMA_BASE_URL: "http://ollama:11434"
  RAG_EMBEDDING_OPENAI_BATCH_SIZE: "20"
  RAG_EMBEDDING_BATCH_SIZE: "20"

  # web search
  ENABLE_RAG_WEB_SEARCH: "true"
  RAG_WEB_SEARCH_RESULT_COUNT: "10"
  RAG_WEB_SEARCH_CONCURRENT_REQUESTS: "10"
  ENABLE_SEARCH_QUERY_GENERATION: "true"
  RAG_WEB_SEARCH_ENGINE: "searxng"

  # searxng
  SEARXNG_QUERY_URL: http://searxng.ai:8080/search?q=<query>

  # image generation
  ENABLE_IMAGE_GENERATION: "false"
  IMAGE_GENERATION_ENGINE: "automatic1111"
  
  # text to speech
  AUDIO_TTS_API_KEY: not_needed
  AUDIO_TTS_OPENAI_API_KEY: not_needed
  AUDIO_TTS_ENGINE: openai
  AUDIO_TTS_MODEL: kokoro
  AUDIO_TTS_OPENAI_API_BASE_URL: http://tts:8880/v1
  AUDIO_TTS_VOICE: af_alloy

  # OIDC
  ENABLE_OAUTH_SIGNUP: "true"
  OAUTH_MERGE_ACCOUNTS_BY_EMAIL: "true"
  # OAUTH_CLIENT_ID: ""
  # OAUTH_CLIENT_SECRET: ""
  OAUTH_SCOPES: "openid email profile"
  OPENID_PROVIDER_URL: "https://auth-k8s.laferriere.app/application/o/open-webui/.well-known/openid-configuration"
  OAUTH_PROVIDER_NAME: "Authentik"
  OPENID_REDIRECT_URI: "https://chat.laferriere.ai/oauth/oidc/callback"