---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations: {}
  labels:
    app: {{ .Values.app.name }}
  name: {{ .Values.app.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: internal-app
        vault.hashicorp.com/agent-inject-template-config.yml: |
          {{`{{- with secret "kv/data/proxmox" -}}
          default:
            user: prometheus@pam
            token_name: exporter
            token_value: {{ .Data.data.token }}
            verify_ssl: false
          {{- end }}`}}
      labels:
        app: {{ .Values.app.name }}
    spec:
      containers:
        - name: {{ .Values.app.name }}
          image: prompve/prometheus-pve-exporter:3.4.5
          command: 
            - /opt/prometheus-pve-exporter/bin/pve_exporter
            - --config.file=/vault/secrets/config.yml
          livenessProbe:
            tcpSocket:
              port: 9221
            initialDelaySeconds: 30
            periodSeconds: 5
          readinessProbe:
            tcpSocket:
              port: 9221
            initialDelaySeconds: 30
            periodSeconds: 5
          ports:
            - containerPort: 9221
          resources: {}
      restartPolicy: Always
status: {}