---
apiVersion: v1
kind: Service
metadata:
  annotations: {}
  labels:
    app: {{ .Values.app.name }}
  name: {{ .Values.app.name }}
spec:
  type: ClusterIP
  ports:
    - name: exporter
      port: 9221
      targetPort: 9221
  selector:
    app: {{ .Values.app.name }}
status:
  loadBalancer: {}