---
apiVersion: v1
kind: Service
metadata:
  annotations:
    nginx.ingress.kubernetes.io/proxy-read-timeout: 3600
    nginx.ingress.kubernetes.io/proxy-send-timeout: 3600
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_http_version 1.1;
      proxy_set_header Connection "Upgrade";
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header X-Forwarded-Host $http_host;
      proxy_set_header X-Forwarded-Proto $scheme;
      proxy_set_header X-Forwarded-For $remote_addr;
      proxy_set_header Host $host;
      proxy_cache_bypass $http_upgrade;
    metallb.universe.tf/loadBalancerIPs: 10.10.10.212
  labels:
    app: {{ .Values.app.name }}
  name: {{ .Values.app.name }}
spec:
  type: LoadBalancer
  ports:
    - name: "{{ .Values.app.name }}"
      port: {{ .Values.app.port }}
      targetPort: {{ .Values.app.port }}
  selector:
    app: {{ .Values.app.name }}

