---
immich:
  image:
    tag: v1.98.2

  immich:
    persistence:
      library:
        existingClaim: nfs-photos

  postgresql:
    metrics:
      enabled: true
    enabled: true

  redis:
    enabled: true

  server:
    service:
      main: 
        type: LoadBalancer