---
searxng:
  env: 
    AUTOCOMPLETE: "true"
  service:
    main:
      type: LoadBalancer
  searxng:
    # https://github.com/searxng/searxng/blob/master/searx/settings.yml
    config:
      use_default_settings: true
      server:
        limiter: false
      # redis:
      #   url: redis://searxng-redis:6379/0
      search:
        autocomplete: "google"
        formats:
          - html
          - json
      ui:
        infinite_scroll: true
  # persistence:
  #   limiter:
  #     enabled: true
  #     type: configMap
  #     name: configmap-searxng-limiter
  #     mountPath: /etc/searxng/limiter.toml
  #     subPath: limiter.toml
  # redis:
  #   enabled: true
  
  resources:
    requests:
      memory: 750Mi
      cpu: 125m
    limits:
      cpu: 400m
      memory: 1Gi
