---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-ini
  namespace: monitoring
data:
  grafana.ini: |
    #[server]
    #  protocol = https
    #  http_port = 3000
    #  cert_file = /etc/grafana/certs/tls.crt
    #  cert_key  = /etc/grafana/certs/tls.key

    [analytics]
      reporting_enabled = false
      check_for_updates = true

    [log]
      mode = console
      level = info

    [paths]
      data         = /var/lib/grafana/
      logs         = /var/log/grafana
      plugins      = /var/lib/grafana/plugins
      provisioning = /etc/grafana/provisioning